apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sweetsocial-ingress
spec:
  rules:
  - host: sweetsocial.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sweetsocial-service
            port:
              number: 3000